language: node_js
    - "8"
install:
    - npm install
cache:
    directories:
        - "node_modules"
script: npm run test:all
before_script:
    - npm install nyc coveralls codeclimate-test-reporter -g
after_script:
    - nyc report --reporter=text-lcov | coveralls
    - codeclimate-test-reporter < ./coverage/lcov.info
